Add dishes to menu
CraftAcademy/SlowFoodApril pull request #19
Opened 2017-05-25 15:48 UTC by benjamincomley

## Add dishes to menu
https://www.pivotaltracker.com/story/show/145100539

- Add dish model
- Add dishes to the correct menu and restaurant
- List dishes in the correct menu together with price
- Create the following dish attributes: Name, Description, Price

2017-05-25 19:44 UTC, tochman requested changes

2017-05-25 19:44 UTC, tochman commented on features/step_definitions/dish_steps.rb
> +  end
Not sure about this block. Can you try to explain each line? What is does and why?

2017-05-25 19:44 UTC, tochman commented on spec/factories/dishes.rb
> +    menu
I would like you to make sure that the dish you create with this factory actually belongs to a menu.

2017-05-25 19:44 UTC, tochman commented on spec/models/dish_spec.rb
> +    it { is_expected.to validate_presence_of :price }
I assume that we don't validate that a dish actually belongs to a menu. That surprises me a bit. Is there a use case where there would be a need for a dish that is NOT associated with a menu?

2017-05-26 09:24 UTC, benjamincomley commented on features/step_definitions/dish_steps.rb
> +  end
Line 6 now reads `hash.delete("restaurant")`

Line 5. Price value in the hash is converted to an integer as the dish model requires the price to be an integer

Line 6. Restauraunt key value is deleted form the hash as the restaurant is only used to make sure that we're getting the correct menu, as searched for on Line 4 in the code (several restaurants could have a breakfast menu). After we've got the correct menu we need to delete the restaurant from the hash before we can call Factory Girl.

Line 7. Factory Girl creates a Dish from the values given in the hash

2017-05-26 09:26 UTC, benjamincomley commented on spec/factories/dishes.rb
> +    menu
Updated Row 6 to `association :menu`
Hopefully this is what you're looking for?

2017-05-26 09:26 UTC, benjamincomley commented on spec/models/dish_spec.rb
> +    it { is_expected.to validate_presence_of :price }
We think this is being checked on Lines 16 through 18?

2017-05-29 10:34 UTC, tochman commented on spec/models/dish_spec.rb
> +    it { is_expected.to validate_presence_of :price }
Yes. I must have missed these specs. Sorry

2017-05-29 10:35 UTC, tochman approved these changes

2017-05-29 11:41 UTC, merged