Create index page with restaurants
CraftAcademy/SlowFoodApril pull request #4
Opened 2017-05-10 15:18 UTC by mmollerstrom

### Create index page with restaurants

https://www.pivotaltracker.com/story/show/145100541

* Created route for the home page
* Created a controller that had a hash with the restaurant names
* Created a view to display restaurant names

2017-05-10 15:30 UTC, tochman requested changes

2017-05-10 15:30 UTC, tochman commented on config/routes.rb
> +  root 'home#index'
Why 2 routes pointing to the same controller? 

I also prefer this syntax:
```
root, controller: :home, action: :index
```

2017-05-10 15:30 UTC, tochman commented on features/index.feature
> +  I would like to be presented with some examples of restaurants that deliver food
Is this the story we had in the Tracker. Feels weird.

2017-05-10 18:11 UTC, mmollerstrom commented on config/routes.rb
> +  root 'home#index'
Fixed!

2017-05-10 18:11 UTC, mmollerstrom commented on features/index.feature
> +  I would like to be presented with some examples of restaurants that deliver food
It was, but I just changed it to a more proper one

2017-05-11 04:57 UTC, tochman commented on features/index.feature
> +  I would like to be presented with some examples of restaurants that deliver food
I would suggest:
````
As a visitor
In order to get information about available restaurants
I would like to see a list of restaurants when I access the application
```
or something like that....

2017-05-11 04:59 UTC, tochman commented on features/index.feature
> +  I would like to be presented with some examples of restaurants that deliver food
Not a blocker though. Please update in Pivotal Tracker and read up on the User Story format.

2017-05-11 04:59 UTC, tochman approved these changes

2017-05-11 04:59 UTC, merged