Add restaurant geo location to the system
CraftAcademy/SlowFoodApril pull request #8
Opened 2017-05-12 08:41 UTC by junydania

## What was done?
      - Implemented geocoder gem to convert the restaurant's full address into geo-coordinates

## What we learnt?
     - How to use the geo coder gem
     - How to use cucumber to check for floats

# PT link
     - https://www.pivotaltracker.com/story/show/145100177

2017-05-12 08:53 UTC, tochman commented
There are conflicts on this one that need to be fixed. @andycarnahan can you help them with that?

2017-05-12 09:17 UTC, junydania commented
Conflict has been resolved.

2017-05-12 10:15 UTC, tochman commented on spec/models/restaurant_spec.rb
IMO you need unit specs for `full_address` and `address_city_state_country_present?` and `address_city_state_country_changed?` (unless you make the last ones `private`)

2017-05-12 10:19 UTC, tochman commented on app/models/restaurant.rb
> +  after_validation  :geocode, if:  :address_city_state_country_present? || :address_city_state_country_changed?
I would place this before any methods but after the validations.

2017-05-12 10:48 UTC, tochman requested changes

2017-05-12 10:48 UTC, tochman commented on spec/models/restaurant_spec.rb
> +    before(:all) do
`before` is enough. No need to use `before(:all)` anymore

2017-05-12 10:48 UTC, tochman commented on spec/models/restaurant_spec.rb
> +      expect(lat).to eq 57.7093164
This tests Geocoder. You should test the Restaurant object's ability to be geocoded. Does that make sense?

2017-05-12 10:48 UTC, tochman commented on spec/models/restaurant_spec.rb
> +    end
You can probably extract this into `rails_helper`.

2017-05-12 12:33 UTC, junydania commented on spec/models/restaurant_spec.rb
Done

2017-05-12 12:33 UTC, junydania commented on app/models/restaurant.rb
> +  after_validation  :geocode, if:  :address_city_state_country_present? || :address_city_state_country_changed?
Done

2017-05-12 12:33 UTC, junydania commented on spec/models/restaurant_spec.rb
> +    before(:all) do
rectified

2017-05-12 12:35 UTC, junydania commented on spec/models/restaurant_spec.rb
> +    end
would appreciate help, when I moved this block to the rails_helper file, I am unable to make the test pass except this block remains in the spec test file.

2017-05-24 07:27 UTC, diraulo commented
@junydania what's the status on this?

2017-05-24 13:07 UTC, junydania commented
@diraulo , @tochman complained about this pull request having the same commit with one other pull request of displaying the user on the map.

This pull request was created off develop.

@tochman kindly advise on the next steps for this pull request. Can this be merged while we resolve the other pull request that has the same commit as this?

2017-06-01 10:37 UTC, tochman approved these changes

2017-06-01 10:37 UTC, merged